// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-nBbP8LMjQEXpqDk2G3b6ORfY8xyZOFI',
    appId: '1:876629588496:web:c22667919fe7089ec92895',
    messagingSenderId: '876629588496',
    projectId: 'prosplit-app',
    authDomain: 'prosplit-app.firebaseapp.com',
    storageBucket: 'prosplit-app.firebasestorage.app',
    measurementId: 'G-D526RZX01M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCma8aqTZBKT6jqTn7u9EJJg5DLCMbX-DU',
    appId: '1:876629588496:android:6d643c8c40ac878cc92895',
    messagingSenderId: '876629588496',
    projectId: 'prosplit-app',
    storageBucket: 'prosplit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY7tCGRypqBfHRlZ8bSoDau2RIsMoyDHA',
    appId: '1:876629588496:ios:1400c1af0aff3a5fc92895',
    messagingSenderId: '876629588496',
    projectId: 'prosplit-app',
    storageBucket: 'prosplit-app.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY7tCGRypqBfHRlZ8bSoDau2RIsMoyDHA',
    appId: '1:876629588496:ios:1400c1af0aff3a5fc92895',
    messagingSenderId: '876629588496',
    projectId: 'prosplit-app',
    storageBucket: 'prosplit-app.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-nBbP8LMjQEXpqDk2G3b6ORfY8xyZOFI',
    appId: '1:876629588496:web:bb56faa8942465a6c92895',
    messagingSenderId: '876629588496',
    projectId: 'prosplit-app',
    authDomain: 'prosplit-app.firebaseapp.com',
    storageBucket: 'prosplit-app.firebasestorage.app',
    measurementId: 'G-7X7CRCSVQ5',
  );

}